version: "2.4"

services:

  ss-server:
    image: ${SSL_IMAGE}
    ports:
      - ${SSL_PORT_R}:${SSL_PORT_R}
    command:
      ss-server
        -s 0.0.0.0
        -p ${SSL_PORT_R}
        -k ${PASSWORD}
        -m ${SSL_METHOD}
        -t 300
        --fast-open
        -u
    restart: always


  server:
    image: ${KCP_IMAGE}
    ports:
      - ${KCP_PORT_R}:${KCP_PORT_R}/udp
    depends_on:
      - ss-server
    command:
      server
        -t ss-server:${SSL_PORT_R}
        -l :${KCP_PORT_R}
        --crypt ${KCP_CRYPT}
        --mode ${KCP_MODE}
        --dscp ${KCP_DSCP}
        --sndwnd ${KCP_RCV}
        --rcvwnd ${KCP_RCV}
        --key ${PASSWORD}
        --quiet
    restart: always


  kcp-client:
    image: ${KCP_IMAGE}
    ports:
      - ${KCP_PORT_C}:${KCP_PORT_C}
    command:
      client
        -r ${ENDPOINT}:${KCP_PORT_R}
        -l :${KCP_PORT_C}
        --crypt ${KCP_CRYPT}
        --mode ${KCP_MODE}
        --dscp ${KCP_DSCP}
        --key ${PASSWORD}
        --sndwnd ${KCP_SND}
        --rcvwnd ${KCP_RCV}
        --log /dev/null
        &


  client:
    image: ${SSL_IMAGE}
    ports:
      - ${SSL_PORT_C}:${SSL_PORT_C}
    depends_on:
      - kcp-client
    command:
      ss-local
        -s kcp-client
        -p ${KCP_PORT_C}
        -m ${SSL_METHOD}
        -k ${PASSWORD}
        -b 0.0.0.0
        -l ${SSL_PORT_C}
        -t 60
        --fast-open
    restart: always


  ss-client:
    image: ${SSL_IMAGE}
    ports:
      - ${SSL_PORT_C}:${SSL_PORT_C}
    command:
      ss-local
        -s ${ENDPOINT}
        -p ${SSL_PORT_R}
        -m ${SSL_METHOD}
        -k ${PASSWORD}
        -b 0.0.0.0
        -l ${SSL_PORT_C}
        -t 60
        --fast-open
    restart: always

